### ISSUE TITLE
unable to create mysql-operator

### ISSUE THREAD

**Issue by gouthamk10** [wagnerjfr/oracle-mysql-operator-innodb-kubernetes#1]
Hi .
need some help in installing mysql-operator
getting the below error

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"

**Comment by wagnerjfr** [comment]
Hi,
I haven't tried this solution for some time now.
Did you setup the Kubernetes cluster locally as described in the README or are you using a different cluster? From where are you taking the mysql-operator helm chart?

**Comment by wagnerjfr** [comment]
I double checked my steps today and it seems to work.

**Comment by wagnerjfr** [comment]
Hi,
How/where do you have your kubernetes setup?
What is the version of it?
```
I cloned the mysql-operator from git hub

git clone git@github.com:oracle/mysql-operator.git
drwxr-xr-x 15 root root 4096 May 19 18:23 mysql-operator

2.the mysql-operator has been copied on my server
after that i cd to the directory
3. cd mysql-operator
4. after that i updated helm repo
helm repo update
[root@k8s-master mysql-operator]# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "presslabs" chart repository
...Successfully got an update from the "banzaicloud-stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

I created name space
kubectl create ns mysql-operator

Then i ran the command to install
helm install mysql-operator mysql-operator
getting the belwo error now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"

please let me know why i am getting the above error.
```

**Comment by gouthamk10** [comment]
[root@k8s-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

[root@k8s-master ~]# kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
k8s-master   Ready    master   14d   v1.18.2
k8s-node1    Ready    <none>   14d   v1.18.2
k8s-node2    Ready    <none>   14d   v1.18.2

thanks
Goutham

**Comment by wagnerjfr** [comment]
The only difference i see is that maybe your kubernetes has a different version i may be using in that project.

Have you tried this steps for setting up k8s locally with vagrant?
https://github.com/wagnerjfr/kubernetes-cluster-environment-vm-vagrant

**Comment by imranrazakhan** [comment]
@wagnerjfr @gouthamk10  since kubernetes 1.16 it support apiversion apps/v1 not apps/v1beta1 in deployment manifest, Currently mysql-operator is not updating(this project is almost dead), you can edit running deployment if possible.
